### ISSUE TITLE
herokuへのデプロイを完了させたい

### ISSUE THREAD

**Issue by terekusa** [terekusa/A-ieba_for_you#82]
## 質問内容・実現したいこと
herokuへのデプロイを完了させたい
## 現状発生している問題・エラーメッセージ
git push heroku main を実行した際に下記エラーが発生

```
remote: -----> Installing node-v16.18.1-linux-x64
remote: -----> Detecting rake tasks
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        rake aborted!
remote:        Sprockets::ArgumentError: link_tree argument must be a directory
remote:        /tmp/build_768fff02/app/assets/config/manifest.js:4
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/directive_processor.rb:407:in `expand_relative_dirname'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/directive_processor.rb:359:in `process_link_tree_directive'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/directive_processor.rb:189:in `block in process_directives'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/directive_processor.rb:187:in `each'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/directive_processor.rb:187:in `process_directives'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/directive_processor.rb:84:in `_call'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/directive_processor.rb:65:in `call'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/processor_utils.rb:84:in `call_processor'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/processor_utils.rb:65:in `reverse_each'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/processor_utils.rb:65:in `call_processors'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/loader.rb:182:in `load_from_unloaded'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/loader.rb:59:in `block in load'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/loader.rb:337:in `fetch_asset_from_dependency_cache'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/loader.rb:43:in `load'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/cached_environment.rb:44:in `block in load'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/map.rb:207:in `block in fetch_or_store'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/map.rb:187:in `fetch'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/map.rb:206:in `fetch_or_store'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/cached_environment.rb:44:in `load'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/bundle.rb:27:in `call'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/processor_utils.rb:84:in `call_processor'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/processor_utils.rb:65:in `reverse_each'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/processor_utils.rb:65:in `call_processors'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/loader.rb:182:in `load_from_unloaded'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/loader.rb:59:in `block in load'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/loader.rb:337:in `fetch_asset_from_dependency_cache'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/loader.rb:43:in `load'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/cached_environment.rb:44:in `block in load'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/map.rb:207:in `block in fetch_or_store'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/map.rb:187:in `fetch'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/map.rb:206:in `fetch_or_store'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/cached_environment.rb:44:in `load'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/base.rb:81:in `find_asset'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/base.rb:88:in `find_all_linked_assets'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/manifest.rb:125:in `each'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/manifest.rb:125:in `to_a'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.0/lib/sprockets/manifest.rb:125:in `block (2 levels) in find'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `block in synchronize'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in `execute'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/promise.rb:564:in `block in realize'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `run_task'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:343:in `block (3 levels) in create_worker'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `loop'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block (2 levels) in create_worker'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `catch'
remote:        /tmp/build_768fff02/vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `block in create_worker'
remote:        Tasks: TOP => assets:precompile
remote:        (See full trace by running task with --trace)
remote: 
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !       Push rejected to a-ieba-for-you.
remote: 

```
## どの処理までうまく動いているのか
RailsアプリとHerokuの紐付けまで完了しています。

## 該当のソースコード
```manifest.js
//= link_tree ../images
//= link application.css
//= link_tree ../../javascript .js
//= link_tree ../../../vendor/javascript .js
```

<img width="219" alt="スクリーンショット 2023-08-02 0 47 14" src="https://github.com/terekusa/A-ieba_for_you/assets/108974592/7a3db16c-1cd2-497d-967f-f2f3c2aa916d">

## エラーから考えられる原因
```
remote:        Sprockets::ArgumentError: link_tree argument must be a directory
remote:        /tmp/build_768fff02/app/assets/config/manifest.js:4
```
上記のように記載があるため、manifest.jsの4行目である
```
//= link_tree ../../../vendor/javascript .js
```
に原因があると考えます。
現在vendorディレクトリは写真の通りの状態となっています。
また、以前[553caee](https://github.com/terekusa/A-ieba_for_you/commit/553caee2548f4f1c76e14b0c84e29c721f8c1989)でcommitした際にvendorファイルごとコミットしてしまい、コミットの取り消し、/vendorを.gitignoreファイルに記載しており、その辺りの取り回しも何か影響しているような気がします。
```.gitigonore
config/settings.local.yml
config/settings/*.local.yml
config/environments/*.local.yml

vendor/
/config/database.yml
/public/uploads
```
## 試したこと
エラー文から検索をかけたところ、
```//= link application.css```
上記部分を変更するという記事を見つけ、確かにscssファイルで記載しているためmanifest.jsの変更だ必要だと思い、修正をかけましたが、そもそもエラーが発生している行が異なるため、エラーは解消しませんでした。
```
//= link_tree ../../../vendor/javascript .js
```
上記部分に関するエラーについての記事は見つからず詰まってしまいました。

**Comment by Tsuchiya2** [comment]
いくつか確認させてください。

- rails new時にどんなオプションを付けてrails newしたのでしょうか。
- herokuへのデプロイは今回は初めてなのでしょうか。以前はデプロイできていたのに急にできなくなったのでしょうか。
- .gitignoreファイルからvendorを外す（gitの対象に含める）状態だとデプロイには成功するのでしょうか。
- `bundle config --local path 'vendor/bundle'`は実行している状況でしょうか。

rails newの際にcssオプションをbootstrapにすると.gitignoreファイルにvendorの記載は無いことを確認しました。上記に書いた「 .gitignoreファイルからvendorを外す（gitの対象に含める）状態だとデプロイには成功するのでしょうか。」辺りを試してみたり、"Sprockets::ArgumentError: link_tree argument must be a directory"がなぜ起きているのかを調べてみたり、検証してみましょう。
